Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [1]:
import numpy as np

In [2]:
array1 = np.random.randint(10, 100, size = 50)

In [3]:
array1

array([78, 52, 80, 14, 65, 37, 35, 18, 75, 21, 71, 93, 53, 78, 28, 65, 45,
       91, 49, 43, 58, 44, 40, 60, 65, 75, 87, 94, 84, 17, 71, 53, 23, 76,
       99, 83, 28, 92, 94, 24, 39, 32, 81, 55, 51, 91, 54, 41, 38, 53])

In [4]:
array1.size

50

In [5]:
array1[5::5]

array([37, 71, 65, 58, 75, 71, 83, 39, 91])

Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [6]:
array2 = np.random.randint(0, 21, size = 30)

In [7]:
array2

array([15,  0,  0, 19, 18,  6, 15, 10,  8, 16, 19,  2,  3, 13, 15,  6,  8,
       14, 15, 15, 13, 13,  8, 10,  5, 11, 13, 13,  9,  0])

In [8]:
array2[1::2]

array([ 0, 19,  6, 10, 16,  2, 13,  6, 14, 15, 13, 10, 11, 13,  0])


Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [11]:
array_enteros = np.random.randint(1, 99, (4,6))

In [12]:
array_enteros

array([[20, 68, 66, 68, 21, 90],
       [ 8, 50, 25, 63,  1, 51],
       [87, 89, 14, 66, 92, 85],
       [53, 73, 53, 85, 47, 25]])

In [20]:
array_decimales = np.random.rand(4,6) + np.random.randint(1, 99, (4,6))
print(array_decimales)

[[50.56600539 21.66867852 16.57585657 42.29138375 64.06258288 90.66124406]
 [10.95129518 44.89795889 27.39086211 28.99469431 93.23910111 50.66984914]
 [73.38943265 21.10868543 87.27657573 38.37558741 34.08711582 37.88353617]
 [72.43226081 63.78991177 53.36922223 55.64675826 44.58600739  1.40582365]]


In [21]:
array_decimales_round = np.round(array_decimales, 2)
print(array_decimales_round)

[[50.57 21.67 16.58 42.29 64.06 90.66]
 [10.95 44.9  27.39 28.99 93.24 50.67]
 [73.39 21.11 87.28 38.38 34.09 37.88]
 [72.43 63.79 53.37 55.65 44.59  1.41]]


In [23]:
array_decimales_round[-1]

array([72.43, 63.79, 53.37, 55.65, 44.59,  1.41])

Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [33]:
array3 = np.random.rand(2,3,5)
print(array3)

[[[0.43018992 0.06927458 0.83662717 0.62979528 0.57516722]
  [0.87486538 0.40069024 0.99004225 0.90579208 0.63468903]
  [0.09192245 0.09467824 0.36065364 0.54704405 0.41636692]]

 [[0.81399539 0.17524227 0.7958705  0.15152569 0.17154804]
  [0.49321912 0.22449916 0.00692627 0.02937403 0.37107942]
  [0.49010866 0.35762197 0.44272448 0.75360064 0.03373556]]]


In [34]:
array3.ndim

3

In [36]:
array3_round = np.round(array3, 1)
print(array3_round)

[[[0.4 0.1 0.8 0.6 0.6]
  [0.9 0.4 1.  0.9 0.6]
  [0.1 0.1 0.4 0.5 0.4]]

 [[0.8 0.2 0.8 0.2 0.2]
  [0.5 0.2 0.  0.  0.4]
  [0.5 0.4 0.4 0.8 0. ]]]


Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente.

In [39]:
array_vacio = np.empty((2,3,5))
print(array_vacio)

[[[0.4 0.1 0.8 0.6 0.6]
  [0.9 0.4 1.  0.9 0.6]
  [0.1 0.1 0.4 0.5 0.4]]

 [[0.8 0.2 0.8 0.2 0.2]
  [0.5 0.2 0.  0.  0.4]
  [0.5 0.4 0.4 0.8 0. ]]]


Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

In [41]:
media = np.mean(array3_round)
print(media)

0.44000000000000006


In [44]:
media_round = np.round(media, 1)
print(media_round)

0.4


In [52]:
np.where(array_vacio == media_round,'A', array_vacio)

array([[['A', '0.1', '0.8', '0.6', '0.6'],
        ['0.9', 'A', '1.0', '0.9', '0.6'],
        ['0.1', '0.1', 'A', '0.5', 'A']],

       [['0.8', '0.2', '0.8', '0.2', '0.2'],
        ['0.5', '0.2', '0.0', '0.0', 'A'],
        ['0.5', 'A', 'A', '0.8', '0.0']]], dtype='<U32')

In [38]:
arraym = np.round(np.random.rand(2, 3, 5), 1)

In [39]:
arraym

array([[[0.1, 0.9, 0.7, 0.2, 0.7],
        [0.5, 0.7, 0.3, 0.7, 0.3],
        [0.7, 0.9, 0.8, 0.3, 0.6]],

       [[0.3, 0.7, 0.1, 0.5, 0.7],
        [0. , 0.4, 0.7, 0.6, 0. ],
        [0.9, 0. , 0. , 0.8, 0.1]]])

In [40]:
arrayi = np.empty((2, 3, 5))

In [41]:
arrayi

array([[[0.1, 0.9, 0.7, 0.2, 0.7],
        [0.5, 0.7, 0.3, 0.7, 0.3],
        [0.7, 0.9, 0.8, 0.3, 0.6]],

       [[0.3, 0.7, 0.1, 0.5, 0.7],
        [0. , 0.4, 0.7, 0.6, 0. ],
        [0.9, 0. , 0. , 0.8, 0.1]]])

In [42]:
mascara_media = np.round(np.mean(arrayi), 1) 
print(mascara_media)
mascara_max = np.max(arrayi)
print(mascara_max)
mascara_min = np.min(arrayi)
print(mascara_min)

0.5
0.9
0.0


In [ ]:
arrayi = np.where(arraym == mascara_media, 'A', np.where(arraym > mascara_media, 'B', 
np.where(arraym == mascara_max, 'D', 
np.where(arraym == mascara_min, 'E', 'C'))))
print(arrayi)

[[['C' 'B' 'B' 'C' 'B']
  ['A' 'B' 'C' 'B' 'C']
  ['B' 'B' 'B' 'C' 'B']]

 [['C' 'B' 'C' 'A' 'B']
  ['E' 'C' 'B' 'B' 'E']
  ['B' 'E' 'E' 'B' 'C']]]



Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [48]:
arrayp= np.random.randint(0, 101, (2,3,5))
print(arrayp)

[[[ 96  90   2  13  93]
  [ 62 100  72  90  86]
  [ 73  43  94  85  45]]

 [[ 10  86   9  17  41]
  [ 48  73  96  13  55]
  [ 14  71  60  16  22]]]


In [ ]:
arrayp[:, :, 0::3] = 0 

In [50]:
print(arrayp)

[[[  0  90   2   0  93]
  [  0 100  72   0  86]
  [  0  43  94   0  45]]

 [[  0  86   9   0  41]
  [  0  73  96   0  55]
  [  0  71  60   0  22]]]


🔍 ¿Qué hace arrayp[:, :, 0::3] = 0?
Este código usa indexación avanzada sobre un array 3D.

Supongamos que arrayp tiene forma (2, 3, 5), es decir:

diff
Copiar
Editar
- 2 bloques (dimensión 0)
- 3 filas por bloque (dimensión 1)
- 5 columnas por fila (dimensión 2)
La expresión arrayp[:, :, 0::3] significa:

Parte	Significado
: (1ª dim)	Todos los bloques
: (2ª dim)	Todas las filas
0::3 (3ª dim)	Columnas en posiciones 0, 3, 6, ...

Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [53]:
arrayp2 = arrayp.reshape(6,5)

In [54]:
arrayp2.ndim

2

In [56]:
arrayi.transpose()

array([[['C', 'C'],
        ['A', 'E'],
        ['B', 'B']],

       [['B', 'B'],
        ['B', 'C'],
        ['B', 'E']],

       [['B', 'C'],
        ['C', 'B'],
        ['B', 'E']],

       [['C', 'A'],
        ['B', 'B'],
        ['C', 'B']],

       [['B', 'B'],
        ['C', 'E'],
        ['B', 'C']]], dtype='<U1')

In [57]:
arrayp2.transpose()

array([[  0,   0,   0,   0,   0,   0],
       [ 90, 100,  43,  86,  73,  71],
       [  2,  72,  94,   9,  96,  60],
       [  0,   0,   0,   0,   0,   0],
       [ 93,  86,  45,  41,  55,  22]])